### ISSUE TITLE
Page not found (BART)

### ISSUE THREAD

**Issue by alanocallaghan** [jcardenas14/genBart#1]
Hi, don't know if you're a BART maintainer, but you seem to be associated with baylorhealth.edu

Either way, when I try to access the demo or the collaborator pages, I get a "Page not found" error.

The addresses shown are:
http://52.25.7.162/bart/
http://52.25.7.162/bart_demo/

This might be a private/public IP issue, or it might be webpages which have been moved.

**Comment by jcardenas14** [comment]
Hi, sorry I am just getting back to you. Yes, I am aware of the BART links being down. This is due to major updates that are in progress. I am in the process of developing an R package through which the app will be accessible and will also most likely be putting a version on shinyapps.io.
